CREATE DATABASE IF NOT EXISTS PEDIDOS;

USE PEDIDOS;

-- CRIAÇÃO DA TABELA COMPRADOR
CREATE TABLE IF NOT EXISTS COMPRADOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

-- CRIAÇÃO DA TABELA FORNECEDOR
CREATE TABLE IF NOT EXISTS FORNECEDOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

-- CRIAÇÃO DA TABELA PRODUTO
CREATE TABLE IF NOT EXISTS PRODUTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL
);

-- CRIAÇÃO DA TABELA PEDIDO
CREATE TABLE IF NOT EXISTS PEDIDO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMPRADOR_ID BIGINT NOT NULL,
    FORNECEDOR_ID BIGINT NOT NULL,
    TOTAL_PRODUTOS INT NOT NULL,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (COMPRADOR_ID) REFERENCES COMPRADOR(ID),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR(ID)
);

-- CRIAÇÃO DA TABELA ITEM_PEDIDO
CREATE TABLE IF NOT EXISTS ITEM_PEDIDO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID BIGINT NOT NULL,
    PRODUTO_ID BIGINT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL_PRODUTO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);