spring:
  application:
    name: pedido-api

  datasource:
    url: jdbc:mysql://localhost:3306/pedidos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
